name: Github Actions Deployment Leantime Gatus

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  Deploy-Leantime:
    name: Deploy Leantime App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definitions/lks-leantime-app.json
          service: lks-leantime-app-service
          cluster: lks-leantime-app
          wait-for-service-stability: true

  Deploy-Gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Config.yml
        run: |
          cat <<EOF > ./config/config.yaml
          alerting:
            github:
              repository-url: "https://github.com/bimbap/lks-leantus"
              token: ${{ secrets.TOKEN }}

          endpoints:
            - name: Leantime
              url: "http://lks-pm-alb-815936537.us-east-1.elb.amazonaws.com"
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                # - "[BODY].status == UP"
                - "[RESPONSE_TIME] <= 500"
              alerts:
                - type: github
                  failure-threshold: 3
                  success-threshold: 5
                  send-on-resolved: true
                  description: "Server down!!"
          EOF
      - name: Build Gatus Images
        run: docker build -t lks-gatus .
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 639134755428.dkr.ecr.us-east-1.amazonaws.com
      - name: Tag Gatus Image
        run: docker tag lks-gatus:latest 639134755428.dkr.ecr.us-east-1.amazonaws.com/lks-gatus:latest
      - name: Push Gatus Image to ECR
        run: docker push 639134755428.dkr.ecr.us-east-1.amazonaws.com/lks-gatus:latest
      - name: Deploy Gatus Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definitions/lks-gatus-app.json
          service: lks-gatus-app-service
          cluster: lks-leantime-app
          wait-for-service-stability: true